# Generated by Django 4.1 on 2023-10-27 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroomapp", "0002_teacher_teacher_user_delete_myuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="classroom",
            name="class_code",
            field=models.CharField(default="", max_length=6, unique=True),
        ),
    ]
