# Generated by Django 4.1 on 2023-10-28 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("classroomapp", "0004_reward_classroom_created_at_classroom_level_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="\\image"),
        ),
        migrations.AddField(
            model_name="mission",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="\\image"),
        ),
        migrations.AddField(
            model_name="reward",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="\\image"),
        ),
        migrations.AddField(
            model_name="student",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="\\image\\student_images"
            ),
        ),
        migrations.AddField(
            model_name="teacher",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="\\image\teacher_images"
            ),
        ),
    ]
